spring:
  application:
    name: Customer Data API
  main:
    web-application-type: servlet

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:local
    username: db
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  h2:
    console.enabled: true

server:
  port: 8282

# Azure OpenAI properties
azure:
  openai:
    endpoint: https://elephantazureopenai.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-08-01-preview
    api-key: ${OPENAI_API_KEY}

  # Azure Search properties
  search:
    endpoint: https://elephant-ai-search.search.windows.net/
    api-key: ${SEARCH_API_KEY}
    index-name: finalindex

